In [1]:
import pandas as pd
from pathlib import Path

In [2]:
#Read csv
#malicious_csv = pd.read_csv('../data/malicious_only_cpy.csv')
#benign_csv = pd.read_csv('../data/benign_out_testing.csv')
all_csv = pd.read_csv('../test_data/featured_data.csv')
#all_csv = malicious_csv.append(benign_csv, ignore_index = True)

C:\Users\danie\AppData\Local\Temp\ipykernel_23508\3689947672.py:4: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  all_csv = pd.read_csv('../test_data/featured_data.csv')

In [3]:

code, uniques = all_csv['tld'].factorize()
all_csv['tld'] = code

code, uniques = all_csv['type'].factorize()
all_csv['type'] = code
all_csv.head()

,type,use_of_ip,abnormal_url,google_index,count.,count-www,count@,count_dir,count_embed_domian,short_url,...,count-,count=,url_length,hostname_length,sus_url,count-digits,count-letters,fd_length,tld,tld_length
0,0,0,0,1,2,0,0,0,0,0,...,1,0,16,0,0,0,13,0,-1,-1
1,1,0,0,1,2,0,0,2,0,0,...,0,0,35,0,0,1,29,5,-1,-1
2,1,0,0,1,2,0,0,3,0,0,...,0,0,31,0,0,1,25,7,-1,-1
3,2,0,1,1,3,1,0,1,0,0,...,1,4,88,21,0,7,63,9,0,2
4,2,0,1,1,2,0,0,1,0,0,...,1,3,235,23,0,22,199,9,1,3

In [4]:
all_csv.tail()

,type,use_of_ip,abnormal_url,google_index,count.,count-www,count@,count_dir,count_embed_domian,short_url,...,count-,count=,url_length,hostname_length,sus_url,count-digits,count-letters,fd_length,tld,tld_length
640189,0,0,0,1,3,0,0,3,0,0,...,0,0,39,0,0,12,21,7,-1,-1
640190,0,0,0,1,2,0,0,4,0,1,...,2,0,44,0,0,7,29,8,-1,-1
640191,0,0,0,1,2,1,0,4,0,1,...,0,0,42,0,0,3,33,7,-1,-1
640192,0,0,0,1,2,0,0,2,0,0,...,0,0,45,0,0,0,36,4,-1,-1
640193,0,0,0,1,2,1,0,3,0,0,...,0,0,41,0,0,0,36,4,-1,-1

In [5]:
#Converting to csv
filepath = Path('../test_data/ready_for_training.csv')
all_csv.to_csv(filepath, index=False)